### ISSUE TITLE
Access-Control-* headers

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/twa#55]
We should identify some best practices for these and add corresponding checks.

**Comment by GatewayBit** [comment]
I'd also like to implement this feature as well.

**Comment by woodruffw** [comment]
Sounds good, thanks for volunteering!

**Comment by GatewayBit** [comment]
@woodruffw 
I'd like to request some feedback for handling Access-Control headers. I believe some of the few important headers we could check for are the following:

- `Access-Control-Allow-Origin`
- `Vary`
- `Access-Control-Allow-Credentials`

**Access-Control-Allow-Origin**
This would be the primary header to check for multiple scenarios. I have a few listed and opinionated response types to go with each.

- `Access-Control-Allow-Origin` header does not exist. (No rating or test provided; skip test entirely)
- `Access-Control-Allow-Origin: *` (**FAIL** -- This resource can be accessed by any domain)
- `Access-Control-Allow-Origin: NULL` (**FAIL** -- The `Origin` header can be crafted to grant access to the resource and is [not recommended to use](https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null)
- `Access-Control-Allow-Origin: https://test-domain.com` (**PASS** -- This header is properly set for access to the `https://test-domain.com`)

**Vary**
If the `Access-Control-Allow-Origin` header is found, we should check for the `Vary` header as well. This may not be required from a security standpoint but could be useful for optimization.

- `Vary: *` header exists (**MEH** -- It's better to replace this header with `Cache-Control: no-store`)
- `Vary` header does not exist (**MEH** -- Include the `Vary` header to enable caching)
- `Vary: https://test-domain.com` header exists (**PASS** -- `Vary` header is included for caching)

**Access-Control-Allow-Credentials**
From a security standpoint this header should generally be included  but may not be suitable for all scenarios.

- `Access-Control-Allow-Credentials` header does not exist (**FAIL** -- This resource requires no authentication to access from outside clients or clients with modified `Origin` request headers)
- `Access-Control-Allow-Credentials: false` (**MEH** -- It's better to remove this response header entirely instead of setting the value to false)
- `Access-Control-Allow-Credentials: true` (**PASS** -- This resource requires credentials to be accessible)

The primary risk factor is the `Origin` request header. It's possible for clients to craft their own `Origin` header to send the server, which can match the `Access-Control-Allow-Origin` value. The solution is to enable authentication on the resource by using the `Access-Control-Allow-Credentials: true` header.

Let me know on your thoughts regarding implementing these checks. I'm open to additional suggestions and edits, thanks!

-Dan

Resources:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary
- https://www.owasp.org/index.php/CORS_OriginHeaderScrutiny
- https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null

**Comment by woodruffw** [comment]
Hey @GatewayBit! Sorry for the late response here:

I like your suggestions for `Access-Control-Allow-Origin` and `Access-Control-Allow-Credentials` and would happily accept a PR for them. I'm a little bit lest certain about the `Vary` checks, since I want `twa` to remain primarily a security-focused script and not a general best-practices/optimization checking tool. Let's go ahead without `Vary` for now, if that works for you.

**Comment by GatewayBit** [comment]
Hello @woodruffw 
Back again for hacktoberfest this year, may I continue forward with completing this task?

**Comment by woodruffw** [comment]
@GatewayBit sure! And thanks again for returning for Hacktoberfest :wink:
